version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - apt-get install -y unzip zip wget || true
      - python3 -m pip install --upgrade pip
      - pip install -r lambdas/requirements.txt
      - pip install pytest
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.2/terraform_1.13.2_linux_amd64.zip
      - unzip terraform_1.13.2_linux_amd64.zip -d /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Preparing Lambda layer..."
      - mkdir -p lambdas/layer/python
      - pip install -r lambdas/requirements.txt -t lambdas/layer/python
      - echo "Validating Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform fmt -recursive
      - terraform validate
      - cd ..
      - echo "Running Python tests..."
      - pytest test/ -v --disable-warnings --maxfail=1

artifacts:
  files:
    - '**/*'
