version: 0.2

env:
  variables:
    LAYER_DIR: "lambdas/layer"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing python dependencies"
      - pip install -r lambdas/requirements.txt -t $LAYER_DIR/python
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.2/terraform_1.13.2_linux_amd64.zip
      - unzip terraform_1.13.2_linux_amd64.zip -d /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Deploying with Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform apply -auto-approve -input=false

artifacts:
  files:
    - '**/*'
