version: 0.2

env:
  variables:
    LAYER_DIR: "lambdas/layer"
    CHECK_DIR: "check"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing system dependencies..."
      - pip install pytest
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.2/terraform_1.13.2_linux_amd64.zip
      - unzip terraform_1.13.2_linux_amd64.zip -d /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Preparing deterministic Lambda layer..."
      - mkdir -p $LAYER_DIR/python
      - REQ_HASH=$(sha256sum lambdas/requirements.txt | awk '{print $1}')
      - |
        if [ ! -f "$CHECK_DIR/.requirements_hash" ] || [ "$(cat $CHECK_DIR/.requirements_hash)" != "$REQ_HASH" ]; then
          echo "Dependencies changed or layer not found, installing..."
          mkdir -p $CHECK_DIR
          python3 -m pip install --no-cache-dir --upgrade-strategy only-if-needed -r lambdas/requirements.txt -t $LAYER_DIR/python
          echo $REQ_HASH > $CHECK_DIR/.requirements_hash
        else
          echo "Layer dependencies unchanged, skipping pip install"
        fi

  build:
    commands:
      - echo "Validating Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform fmt -recursive
      - terraform validate
      - cd ..
      - echo "Running Python tests..."
      - pytest test/ -v --disable-warnings --maxfail=1

artifacts:
  files:
    - '**/*'
  discard-paths: no
  exclude-paths:
    - .terraform/**

cache:
  paths:
    - $LAYER_DIR/python/**/*
    - $CHECK_DIR/.requirements_hash
