version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - yum install -y make zip || apt-get update && apt-get install -y make zip || true
      - pip install -r lambdas/requirements.txt
      - pip install pytest

  build:
    commands:
      - echo "Packaging Lambda functions..."
      - make all
      - echo "Running Terraform validation..."
      - cd terraform
      - terraform fmt -check
      - terraform validate
      - cd ..
      - echo "Running Python tests..."
      - pytest tests/ -v

artifacts:
  files:
    - build/*.zip
    - terraform/**
