version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Terraform..."
      - yum install -y unzip wget || true
      - wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      - unzip terraform_1.9.8_linux_amd64.zip -d /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Deploying with Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform apply -auto-approve -input=false

artifacts:
  files:
    - '**/*'
