name: Gitback Sync UAT -> Dev

# Trigger workflow only on push to uat
on:
  push:
    branches:
      - uat

jobs:
  gitback-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push branches

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history

      # Step 2: Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Create or update persistent sync branch
      - name: Prepare uat-sync branch
        run: |
          git fetch origin dev
          git fetch origin uat
          # Checkout existing uat-sync or create from dev
          if git show-ref --verify --quiet refs/heads/uat-sync; then
            git checkout uat-sync
          else
            git checkout -b uat-sync origin/dev
          fi
          # Merge uat changes
          git merge origin/uat --no-ff -m "Sync hotfix from uat to dev"

      # Step 4: Push uat-sync branch
      - name: Push uat-sync branch
        run: |
          git push origin uat-sync

      # Step 5: Create PR using GitHub CLI
      - name: Create PR to dev
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --base dev --head uat-sync --json number --jq '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            gh pr create --base dev --head uat-sync --title "Gitback Sync: uat -> dev" --body "Automated PR to sync changes from uat to dev." --draft=false
          else
            echo "PR already exists: #$PR_EXISTS"
          fi
