name: Gitback Sync UAT -> Dev

on:
  push:
    branches:
      - uat

jobs:
  gitback-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push branches

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history

      # Step 2: Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Create or update persistent sync branch
      - name: Prepare uat-sync branch
        run: |
          git fetch origin
          # If uat-sync exists, check it out, otherwise create from dev
          if git ls-remote --exit-code --heads origin uat-sync; then
            git checkout uat-sync
            git pull origin uat-sync
          else
            git checkout -b uat-sync origin/dev
          fi
          # Merge latest uat into uat-sync
          git merge origin/uat --no-ff -m "Sync hotfix from uat to dev"

      # Step 4: Push uat-sync branch (force to avoid non-fast-forward issues)
      - name: Push uat-sync branch
        run: |
          git push origin uat-sync --force

      # Step 5: Create PR using GitHub CLI
      - name: Create PR to dev
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --base dev --head uat-sync --json number --jq '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            gh pr create --base dev --head uat-sync --title "Gitback Sync: uat -> dev" --body "Automated PR to sync changes from uat to dev."
          else
            echo "PR already exists: #$PR_EXISTS"
          fi
